# Generated by Django 4.2.2 on 2023-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedecine', '0004_rapport_image_dicom_alter_image_dicom_destinataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_dicom',
            name='parent_series',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
